using System.Collections.Generic;

namespace Grpc.Core;

/// <summary>
/// Stores mapping of methods to server call handlers.
/// Normally, the <c>ServerServiceDefinition</c> objects will be created by the <c>BindService</c> factory method 
/// that is part of the autogenerated code for a protocol buffers service definition.
/// </summary>
public class ServerServiceDefinition
{
    readonly IReadOnlyList<Action<ServiceBinderBase>> addMethodActions;

    internal ServerServiceDefinition(List<Action<ServiceBinderBase>> addMethodActions)
    {
        this.addMethodActions = addMethodActions.AsReadOnly();
    }

    /// <summary>
    /// Forwards all the previously stored <c>AddMethod</c> calls to the service binder.
    /// </summary>
    public void BindService(ServiceBinderBase serviceBinder)
    {
        foreach (var addMethodAction in addMethodActions)
        {
            addMethodAction(serviceBinder);
        }
    }

    /// <summary>
    /// Creates a new builder object for <c>ServerServiceDefinition</c>.
    /// </summary>
    /// <returns>The builder object.</returns>
    public static Builder CreateBuilder()
    {
        return new Builder();
    }

    /// <summary>
    /// Builder class for <see cref="ServerServiceDefinition"/>.
    /// </summary>